export const ENVIRONMENT_KEYS = {
  VITE_CLIENT_URL: import.meta.env.VITE_CLIENT_URL,
  VITE_API_URL: import.meta.env.VITE_API_URL,
  VITE_API_URL_REFRESH_TOKEN: import.meta.env.VITE_API_URL_REFRESH_TOKEN,
  VITE_ENCRYPTION_KEY: import.meta.env.VITE_ENCRYPTION_KEY,
  VITE_ENCRYPTION_IV: import.meta.env.VITE_ENCRYPTION_IV,
  VITE_SENTRY_URL: import.meta.env.VITE_SENTRY_URL,
  VITE_OPEN_STREET_MAP_API_URL: import.meta.env.VITE_OPEN_STREET_MAP_API_URL
}
