export const PATH = {
  HOME: '/',
  GENERATOR: '/generator',
  NOTIFICATION: '/notification',
  WORKSPACE: '/workspace',
  CREATE_WORKSPACE: '/create-workspace',
  EDIT_WORKSPACE: '/edit-workspace',
  ACCOUNT: '/account',
  LOGIN: '/login',
  WEBCLIENT_INFIELD: '/webclient-infield',
  CREATE_ACCOUNT: '/create-account',
  EDIT_ACCOUNT: '/edit-account/:accountId',
  SHARING_ACCOUNT: '/share-account/:accountId',
  SHARING_WORKSPACE: '/share-workspace/:workspaceId',
  CREATE_CONTACTINFO: '/create-contactinfo',
  EDIT_CONTACTINFO: '/edit-contactinfo/:contactInfoId',
  WEBCLIENT_INFIELD_CONTACT: '/webclient-infield-contact',
  VAULT: '/vault',
  VAULT_SETTINGS: '/vault/settings',
} as const
